added basic models
cmu-delphi/signal_documentation pull request #1
Opened 2023-04-24 16:35 UTC by BrainIsDead

2023-04-26 14:38 UTC, krivard commented on src/datasources/models.py
> +    )
From discussion over zoom:

* one base name can apply to many signals; each signal _currently_ has only one base name
* it's not always clear which signal should be the base name among a group of related signals (example: fb-survey signals used to use the unweighted signal as base; now use weighted signal as base)
* prototype sheet already has {base_name} {base_description} etc populated in the display name and description text; not sure how we want to handle this in the app (options: (1) use fully-populated text in the app; (2) use & permit templated text in the app... (2) is probably better but we should write down how we want it to work so it's clear how to implement it)

2023-04-26 15:14 UTC, BrainIsDead commented on src/datasources/models.py
> +    )
Done

2023-04-26 15:14 UTC, BrainIsDead commented on src/datasources/models.py
> +    )
Done

2023-04-26 15:14 UTC, BrainIsDead commented on src/datasources/models.py
> +        help_text=_('Format'),
Done

2023-04-26 15:14 UTC, BrainIsDead commented on src/datasources/models.py
> +    )
Done, but will be changed to models

2023-04-26 15:15 UTC, BrainIsDead commented on src/datasources/models.py
> +    )
Done

2023-04-28 14:06 UTC, BrainIsDead commented
> Comments inline -- it feels like some of this code was maybe premature? I'm used to discussing data models in diagrams first so everyone's on the same page with what the relationships are and where they belong. Django is beautifully concise, but not as concise as a drawing 😄

![models](https://user-images.githubusercontent.com/24429352/235169887-9ab669c8-bbe3-4124-a899-3a7fed1b535e.png)

2023-05-05 21:41 UTC, krivard requested changes
Some cleanup, a question for Carlyn, and a question about LinkTypes

2023-05-05 21:41 UTC, krivard commented on src/base/models.py
> +    )
We need to support the following anchor text on links[1]:

* DUA
* API Documentation
* Interpreting mask use in context
* Question text
* Survey details
* Survey documentation
* Technical description
* Wave 10 revision updates
* Wave 11 revision updates

Will `LinkType` do this, or does Django support a way to include an extra column on the many-to-many table(s) between Link and the things-that-have-links, or do we need something else?

[1] I pulled a unique list of anchor text from the Source and Signals sheets into [a scratch page on the MVP sheet](https://docs.google.com/spreadsheets/d/168ePK0XAzlGKvtYItpQlX6Gh0CHlLKNqd185GYWEA24/edit#gid=792762620)

2023-05-08 14:55 UTC, carlynvandyke commented on src/signals/models.py
> +    )
Just discussed this with Mike- we are going to make it many-to-many.

2023-05-08 20:48 UTC, krivard requested changes
* Minor adjustment to time labels
* Exhaustively reviewed deletion methods (thanks for the reminder)
* Found a capitalization spelling i missed before (sorry)

2023-05-08 20:48 UTC, krivard commented on src/base/models.py
> +    SURVEY_DETAILS = 'survey_details', _('SURVEY_DETAILS')
```suggestion
    SURVEY_DETAILS = 'survey_details', _('Survey details')
```

2023-05-08 20:48 UTC, krivard commented on src/datasources/models.py
> +        on_delete=models.SET_NULL,
use PROTECT here: the system shouldn't let you delete a DataSource until its subdivisions have either been deleted or reassigned

I would also accept CASCADE but I don't feel strongly either way; use your favorite

2023-05-08 20:48 UTC, krivard commented on src/signals/models.py
> +        on_delete=models.SET_NULL,
use PROTECT here: the system should not let you delete a signal until its related signals have been reassigned

2023-05-08 20:48 UTC, krivard commented on src/signals/models.py
> +        on_delete=models.SET_NULL,
confirming SET_NULL: if a pathogen is deleted, the signals for that pathogen should be reassigned to the null pathogen

2023-05-08 20:48 UTC, krivard commented on src/signals/models.py
> +        on_delete=models.SET_NULL,
confirming SET_NULL: if a category is deleted, the signals in that category should be reassigned to the null category

2023-05-08 20:48 UTC, krivard commented on src/signals/models.py
> +        on_delete=models.PROTECT
confirming PROTECT: the system should not let you delete a source subdivision until the signals from that subdivision have either been deleted or reassigned

i would also accept CASCADE here but i don't feel strongly either way so use your favorite

2023-05-08 20:48 UTC, krivard commented on src/signals/models.py
> +        help_text=_('Signal base'),
is this useful or no?

```suggestion
        related_name='base_for',
        help_text=_('Signal base'),
```

2023-05-08 20:48 UTC, krivard commented on src/signals/models.py
> +    DATE = 'week', _('Week')
Unfortunately we do need all three:
* Day
* Date
* Week

2023-05-08 21:06 UTC, BrainIsDead commented on src/base/models.py
> +    SURVEY_DETAILS = 'survey_details', _('SURVEY_DETAILS')
thanks, I just automatically copypasted

2023-05-08 21:07 UTC, BrainIsDead commented on src/base/models.py
> +    SURVEY_DETAILS = 'survey_details', _('SURVEY_DETAILS')
fixed

2023-05-09 19:45 UTC, krivard approved these changes
👍 Looks good!

2023-05-09 20:16 UTC, merged