Sd 27 tests
cmu-delphi/signal_documentation pull request #14
Opened 2023-07-25 13:49 UTC by BrainIsDead

Resolve SD-27:
- Added `link_preview` import in `models.py`
- Modified `get_preview` method in `Link` model to return `LinkPreview` object
- Added `SignalListViewTest` class in `tests.py`
- Added test methods for `SignalListView` in `tests.py`
- Modified `get_queryset` method in `SignalsListView` to call `get_base_diffs` for each object in the queryset
- Added `get_context_data` method in `SignalsListView`
- Modified `name` and `display_name` fields in `DataSourceFactory` to use a sequence with a prefix.
- Modified `name` and `display_name` fields in `SourceSubdivisionFactory` to use a sequence with a prefix.
- Modified `description` field in `SourceSubdivisionFactory` to generate fake text with a maximum of 250 characters.
- Modified `name` field in `GeographyFactory` to use a sequence with a prefix.
- Modified `name` field in `PathogenFactory` to use a sequence with a prefix.
- Modified `name` field in `SignalCategoryFactory` to use a sequence with a prefix.
- Modified `name` field in `SignalTypeFactory` to use a sequence with a prefix.
- Modified `name` field in `SignalFactory` to use a sequence with a prefix.
- Modified `short_description` and `description` fields in `SignalFactory` to generate fake text with a maximum of 500 characters.
- Added test cases for filtering and searching in `SignalListViewTest`.
- Added test cases for `SignalDetailViewTest`.
- Removed unnecessary code in `SignalsListView` view.

2023-07-25 15:00 UTC, krivard reviewed
It looks like the factories for creating fake data and the tests themselves are all mixed in with production files. Historically, we've tried to avoid putting test files in directories that get deployed to production wherever possible. Does Django permit isolating tests from core app functionality or do they have to be in the same directories as the production code?

2023-07-25 15:13 UTC, BrainIsDead commented on src/base/factories.py
> +fake = Faker()
Creates fake data for tests similar to real

2023-07-25 15:14 UTC, BrainIsDead commented
> It looks like the factories for creating fake data and the tests themselves are all mixed in with production files. Historically, we've tried to avoid putting test files in directories that get deployed to production wherever possible. Does Django permit isolating tests from core app functionality or do they have to be in the same directories as the production code?

I can move it to tests

2023-07-26 16:50 UTC, krivard approved these changes
👍 structure looks good! I'm not sure how view tests work but hopefully @nolangormley can cover those (`src/signals/tests/tests.py`)

2023-07-26 16:50 UTC, krivard commented on src/datasources/tests/factories.py
> +    display_name = Sequence(lambda n: f'subdicision_display_name_{n}')
```suggestion
    name = Sequence(lambda n: f'subdivision_name_{n}')
    display_name = Sequence(lambda n: f'subdivision_display_name_{n}')
```

2023-07-27 17:10 UTC, nolangormley requested changes
Could you get tests running in CI? I can't seem to get this running on my local with docker nor through pipenv.

2023-07-31 18:41 UTC, BrainIsDead commented on src/datasources/tests/factories.py
> +    display_name = Sequence(lambda n: f'subdicision_display_name_{n}')
Done

2023-07-31 18:46 UTC, BrainIsDead commented
> Could you get tests running in CI? I can't seem to get this running on my local with docker nor through pipenv.
added `python /usr/src/signal_documentation/src/manage.py tests` to docker-compose

2023-08-09 16:40 UTC, nolangormley approved these changes
LGTM

2023-08-11 14:07 UTC, merged